### PR TITLE
reordered text & sg rendering code to optimize.

### PR DESCRIPTION
**Pull request by prime6809**
reordered text & sg rendering code to optimize.
added ability to use Dragon 200E style fonts
added a bunch of fonts, have not added Atom code to select them, but can be selected on the Dragon.
We might want to rewrite attom command code to allow commands to take a parameter such as the font no to set.

### CODE REVIEW

**Comment by cmoulang** [comment]
Merge changes

**Comment by cmoulang** [comment]
Merge pull request

**Comment by cmoulang** [comment]
There is a compile error when target is atomvga.

[build] /home/pdev2/Documents/pico_atomvga/atomvga.c:467:9: error: 'fontdata' undeclared (first use in this function); did you mean 'font_t'?
[build]   467 |         fontdata = fontdata_6847;
[build]       |         ^~~~~~~~
[build]       |         font_t

**Comment by hoglet67** [comment]
There is one aspect of this change that seems a step backwards.

do_test() is now doing a bit more work in the inner loop (i.e. each character):

Previously the font data was accessed directly via a pointer called fontdata.

Now this pattern is used:
uint8_t b = fonts[fontno].fontdata[(ch &amp; 0x3f) * 12 + sub_row];

(i.e. an extra array/structure indirection).

This is going to cost cycles.

Also, the way the code is structured, for lower case that expression is evaluated twice:
https://github.com/prime6809/pico_atomvga/blob/0be44e3e26eeab40683ca0ca15cadfd0ebf15920/atomvga.c#L615

I would say this needs tidying up before this is merged.

Dave

**Comment by prime6809** [comment]
I've changed it to have a local fontptr, which is assigned once outside the loop from the selected font. This restores the previous behavior. I also added the ability to set the text and background colours in text mode. Do I need another push request?

**Comment by hoglet67** [comment]
No, this one is still open (against your master branch), so any additional commits just get included until it is merged.

I'll defer to Chris to merge this one.

It compiles for me now; I've not tested on real hardware, as something else is on the bench at the moment.

BTW, there is still some scope for optimizing the inner loop of the text rendering slightly. The variable sub_row is added each time, even though is is a constant. This could be added to once to fontdata at the start of do_text. Also, the font data is currently uses 12 bytes per character. If it used 16 bytes per character, this woul simplify some of the calculations.

**Pull request merged**
